[phases.setup]
nixPkgs = ["go_1_23"]

[phases.install]
cmds = [
    "go mod download"
]

[phases.build]
cmds = [
    "CGO_ENABLED=0 GOOS=linux go build -o auth-service ./cmd/main.go"
]

[start]
cmd = "./auth-service"
