[phases.setup]
nixPkgs = ["go_1_23"]

[phases.install]
cmds = [
    "cd /app && cp -r shared /tmp/shared",
    "cd /app/services/auth-service && go mod download"
]

[phases.build]
cmds = [
    "cd /app && cp -r /tmp/shared .",
    "cd /app/services/auth-service && CGO_ENABLED=0 GOOS=linux go build -o auth-service ./cmd/main.go"
]

[start]
cmd = "cd /app/services/auth-service && ./auth-service"
